spring:

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:authH2
    username: sa
    password:
    platform: dev

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop