spring:
  application:
    name: ysf-authorization-server
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://sql7.freesqldatabase.com:3306/sql7284585"
    username: "sql7284585"
    password: "dyUIuNYFaW"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 800
  jpa:
    hibernate:
      ddl-auto: create-drop
