spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Auth-Service

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://sql7.freesqldatabase.com:3306/sql7284585"
    username: "sql7284585"
    password: "dyUIuNYFaW"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 800
  jpa:
    hibernate:
      ddl-auto: create-drop

config:
  oauth2:
    privateKey: -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAwSgjDCD/CP5TW2EcowNixaxcxV4TTGeM6PA4/N0JoBD7uOQd
      xRk1mtOWBZmBnZ8ptTsQJg84tsaUn7EpS9WnbXZHUEHseQk4pMmAC/9C1x/peMW+
      3oSIBWzkKQV8Qj0dLfJzgguc1jE8urGCOAM/g+cWIgqZHCRGdNlr1GFq1ow2V2s/
      sBwP03AKN3MMPPDUlshsiPJTqvRChEWYxmNEKGmJs1LRXeHgp4ZNtcWc22LYw8G2
      rdbwhVlkG9VAsMi6XcidmZfn+KBvCvgVCZ9SUMyH+ZPiKcf4WhaM2MSutKWEwuot
      z6w23LN47RP7E5EQYTX754jbkpQASz43GPyDeQIDAQABAoIBAQC0tdpkRJKWVWqj
      OW3TTR2hlqqMtIEVoGOCowyN9jZFHN6EklcPyZAPNBlNT9qmHvykY4euM9t5lLwD
      03mxS0iC7n+1pJeafXgTI7m6f6yHG4IQzeDOyeuAN+oWPt2MEyUzkXtjlX28HwCU
      IfKUeOV5gD+CxauNWprYQ3nQjvunkJI3TO+t0mYaI77cU3fUbLG6mAVoF1R/AQ3y
      PCYX5V6GFdoAZxu/fLHxu9yfgkijsT27bEA+emlSc6JIKON9nJe3SLsq08b5Rk7r
      C9Gu+YbwpLRAaPGWUKygtr7RcHy2+B3C0rbGddqEVQmMg/VS8ED9mY7nXWeDKLEu
      ya1YcrzpAoGBAOJevDDeQlIU4dQVDl9aCXTaQP4p9aKiUilMttuWmrILgysstweu
      Mf29in0fgRoCRK7Aw6Mb3r37lCcObPNetQbweQduCU6mctBOBiuuyEXoDsnivzJ6
      IlEAW6pLMg9TxlpCuUZFf4XPdZEM17QBsGN+QD8xDy5YVjNTsMX9qvuPAoGBANpw
      e6gfZIBGPiShqUYRThvonLVGOZKAyA5DocbUzJPEwDlXFNomoQ7vkierDnU+zUaP
      I2eFzNe5LAm0zd7ABu+Ta6aOOv61N7cIQTIzcAERifDfPJ/bU8YGOD53OtVkNV1g
      THRMa5mRyDtKXzEJnuyTfH6oHHk6EtPojS6x6yx3AoGAdFDvbEDYXSrju0EyiGZQ
      U53OJYtT70Ru6U/E6eJiDLiDpsysI6MrhtE89vwYL1AZEJ52KDqq4n4B62urKgZx
      CGbKGbo9yA8ZEdX1r754pAsQhkYfroU5WtvPPhqzV1LZqgl9ABG36/7kzyqFL7Zq
      d0UpKA9CWLMFYAxR2fp1QBsCgYAEWl18ejOsgrnWTQpshQfDcp0814tqKfrSnfJp
      XfA9uZwDCIM33bEz9P46oCQHnhrFHzEbbQUp/1yrTNkVaUo6F/v7M7ZlQQM9OILk
      FzZSLyFKlYhFvz8qIRGZ3RJlEjwmAjdD0goK42bUF6VR+tkZ6c5/T6ZRnCCn7Ghz
      18PR/QKBgAq+6YL04zZTmrFLx7TP7Eo5myOBMxZDeYKzozEYUpfwyO4F/N4pr05O
      TybONT6nl10Itn+nQpX+iS5tOgd0LX3JMy1UyvNkSeEi/lYlJLzLx9M38RYuixsa
      WlgdqWtExRFGRQ22waaFLJdhkHonw2ec/5qgIjt9qdPdPBPvdwRA
      -----END RSA PRIVATE KEY-----
    publicKey: -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwSgjDCD/CP5TW2EcowNi
      xaxcxV4TTGeM6PA4/N0JoBD7uOQdxRk1mtOWBZmBnZ8ptTsQJg84tsaUn7EpS9Wn
      bXZHUEHseQk4pMmAC/9C1x/peMW+3oSIBWzkKQV8Qj0dLfJzgguc1jE8urGCOAM/
      g+cWIgqZHCRGdNlr1GFq1ow2V2s/sBwP03AKN3MMPPDUlshsiPJTqvRChEWYxmNE
      KGmJs1LRXeHgp4ZNtcWc22LYw8G2rdbwhVlkG9VAsMi6XcidmZfn+KBvCvgVCZ9S
      UMyH+ZPiKcf4WhaM2MSutKWEwuotz6w23LN47RP7E5EQYTX754jbkpQASz43GPyD
      eQIDAQAB
      -----END PUBLIC KEY-----
    clientid: foio_auth_service
    clientSecret: 70fNdOLmlKZMfpDa9KCV/iGB/ff7xk2WO5w8XSeMDdc=