spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:authH2
    username: sa
    password:
    platform: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    url: jdbc:h2:mem:authH2
    schemas: authH2
    user: sa
    password:
    locations: classpath:db/migration/h2
    validate-on-migrate: true
    enabled: false