version: '3.7'

services:

  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer
    ports:
      - 9000:9000

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  auth-service:
    container_name: auth-service
    hostname: auth-service
    image: docker.pkg.github.com/foiok/auth-service/auth-service:1.5.0-snapshot
    ports:
      - 8080:8080