CREATE TABLE IF NOT EXISTS PERMISSION
(
    ID   BIGINT       NOT NULL AUTO_INCREMENT
        PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
)
    ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS ROLE
(
    ID   BIGINT       NOT NULL AUTO_INCREMENT
        PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
)
    ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS ROLE_PERMISSION
(
    ID            BIGINT NOT NULL AUTO_INCREMENT
        PRIMARY KEY,
    PERMISSION_ID BIGINT NULL,
    ROLE_ID       BIGINT NULL
)
    ENGINE = MYISAM;

CREATE INDEX R_P_I_R_I
    ON ROLE_PERMISSION (ROLE_ID);

CREATE INDEX R_P_I_P_I
    ON ROLE_PERMISSION (PERMISSION_ID);

CREATE TABLE IF NOT EXISTS USER
(
    ID          BIGINT       NOT NULL AUTO_INCREMENT
        PRIMARY KEY,
    CODE        BIGINT       NOT NULL,
    CREATE_TIME DATETIME     NOT NULL,
    EMAIL       VARCHAR(255) NOT NULL,
    NICKNAME    VARCHAR(255) NOT NULL,
    PASSWORD    VARCHAR(255) NOT NULL,
    USER_STATUS INT          NOT NULL
)
    ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS USER_ROLE
(
    ID        BIGINT NOT NULL AUTO_INCREMENT
        PRIMARY KEY,
    USER_CODE BIGINT NOT NULL,
    ROLE_ID   BIGINT NULL
)
    ENGINE = MYISAM;

CREATE INDEX U_R_I_R_I
    ON USER_ROLE (ROLE_ID);