package com.wojo.authservice.exception

enum class ErrorCode {

    UNAUTHORIZED,
    NOT_FOUND,
    NOT_ACTIVATED_YET,
    BLOCKED,
    CREATED_INCORRECT,
    DELETED,
    MODIFIED_INCORRECT,
    BLANK_USERNAME,
    BLANK_PASSWORD,
    BLANK_EMAIL,
    INVALID_EMAIL_FORMAT,
    DUPLICATE_EMAIL,
    DUPLICATE_NICKNAME
}