name: prod build

on:
  push:
    branches:
      - master
      - 'feature/**'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: run test
        run: mvn clean verify

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@master
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Deploy docker image with maven
        run: mvn clean package dockerfile:push -DskipTests -Ddockerfile.skip=false -Ddockerfile.username=FoioK -Ddockerfile.password=${{ secrets.DOCKER_TOKEN }}
